#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -eu
# shellcheck disable=SC1091
[ -r /etc/conf.d/probeos-web ] && . /etc/conf.d/probeos-web
exec /usr/bin/python3 /usr/local/lib/probeos/probeos_web.py \
    --bind "${PROBEOS_WEB_BIND:-127.0.0.1}" \
    --port "${PROBEOS_WEB_PORT:-8080}" \
    --report-dir "${PROBEOS_REPORT_DIR:-/run/probeos}"
