#!/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# ProbeOS Openbox autostart
# https://probeos.eu
# © 2026 Ploos AS

# Set wallpaper
[ ! -f /usr/share/probeos/wallpaper.png ] || feh --bg-scale /usr/share/probeos/wallpaper.png &

# Panel
tint2 &

# Launch ProbeOS GUI
/usr/local/bin/gui-menu.sh &
